cache_config={'CACHE_TYPE': 'simple'}
consumer_key="XXXXXX"
consumer_secret="XXXXXX"
access_token="XXXXXX-XXXXXX"
acess_token_secret="XXXXXX"
MLapikey = 'XXXXXX'
MLurl = 'XXXXXX://XXXXXX.XXXXXX-XXXXXX.XXXXXX-XXXXXX.XXXXXX.XXXXXX.XXXXXX.XXXXXX/XXXXXX/XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX'